
 export const productsArray = [
    {
      id: 1,
      image: "./Images/1.png",
      title: "JBL",
      price: "8400",
    },
    {
      id: 2,
      image: "./Images/1.png",
      title: "Bose",
      price: "5000",
    },
    {
      id: 3,
      image: "./Images/1.png",
      title: "Sony",
      price: "6000",
    },
    {
      id: 4,
      image: "./Images/1.png",
      title: "Apple",
      price: "4000",
    },
    {
      id: 5,
      image: "./Images/1.png",
      title: "Sennheiser",
      price: "9900",
    },
    {
      id: 6,
      image: "./Images/1.png",
      title: "Audio-Technica",
      price: "4450",
    },
    {
      id: 7,
      image: "./Images/1.png",
      title: "Beyerdynamic",
      price: "3500",
    },
    {
      id: 8,
      image: "./Images/1.png",
      title: "Beats",
      price: "4000",
    },
    {
      id: 9,
      image: "./Images/1.png",
      title: "Acousticom",
      price: "9000",
    },
    {
      id: 10,
      image: "./Images/1.png",
      title: "Boat",
      price: "18000",
    },
    {
      id: 10,
      image: "./Images/1.png",
      title: "Boat",
      price: "18000",
    },
    {
      id: 10,
      image: "./Images/1.png",
      title: "Boat",
      price: "18000",
    },
    {
      id: 10,
      image: "./Images/1.png",
      title: "Boat",
      price: "18000",
    },
    {
      id: 8,
      image: "./Images/1.png",
      title: "Beats",
      price: "4000",
    },
    {
      id: 8,
      image: "./Images/1.png",
      title: "Beats",
      price: "4000",
    },
    {
      id: 8,
      image: "./Images/1.png",
      title: "Beats",
      price: "4000",
    },
    {
      id: 5,
      image: "./Images/1.png",
      title: "Sennheiser",
      price: "9900",
    },
    {
      id: 6,
      image: "./Images/1.png",
      title: "Audio-Technica",
      price: "4450",
    },
    {
      id: 5,
      image: "./Images/1.png",
      title: "Sennheiser",
      price: "9900",
    },
    {
      id: 6,
      image: "./Images/1.png",
      title: "Audio-Technica",
      price: "4450",
    },
    {
      id: 6,
      image: "./Images/1.png",
      title: "Audio-Technica",
      price: "4450",
    },
    {
      id: 5,
      image: "./Images/1.png",
      title: "Sennheiser",
      price: "9900",
    },
    {
      id: 6,
      image: "./Images/1.png",
      title: "Audio-Technica",
      price: "4450",
    },
    {
      id: 6,
      image: "./Images/1.png",
      title: "Audio-Technica",
      price: "4450",
    },
    {
      id: 5,
      image: "./Images/1.png",
      title: "Sennheiser",
      price: "9900",
    },
    {
      id: 6,
      image: "./Images/1.png",
      title: "Audio-Technica",
      price: "4450",
    },
    {
      id: 6,
      image: "./Images/1.png",
      title: "Audio-Technica",
      price: "4450",
    },
    {
      id: 5,
      image: "./Images/1.png",
      title: "Sennheiser",
      price: "9900",
    },
    {
      id: 6,
      image: "./Images/1.png",
      title: "Audio-Technica",
      price: "4450",
    },
    {
      id: 6,
      image: "./Images/1.png",
      title: "Audio-Technica",
      price: "4450",
    },
    {
      id: 5,
      image: "./Images/1.png",
      title: "Sennheiser",
      price: "9900",
    },
    {
      id: 6,
      image: "./Images/1.png",
      title: "Audio-Technica",
      price: "4450",
    }
  ];